"""Recreating initial migration

Revision ID: 476e750e10c1
Revises: b4bc49a9ecea
Create Date: 2025-03-20 01:03:53.572183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476e750e10c1'
down_revision = 'b4bc49a9ecea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
